### ISSUE TITLE
[BUG] action-hosting-deploy fails with Node v12

### ISSUE THREAD

**Issue by nappernick** [FirebaseExtended/action-hosting-deploy#204] opened 2022-05-18 23:21 UTC
### Error message
 /opt/hostedtoolcache/node/12.22.12/x64/bin/npx firebase-tools hosting:channel:deploy pr2057-pricing_breakdown_si --only cms --expires 7d --project guesthouse-cms-dev --json
  
  Firebase CLI v11.0.0 is incompatible with Node.js v12.22.12 Please upgrade Node.js to version >= 14.18.0
  
  The process '/opt/hostedtoolcache/node/12.22.12/x64/bin/npx' failed with exit code 1

### Expected behavior
Preview builds with Node v12.22

### Actual behavior
Channel preview build fails due to the use of the newest version of `firebase-tools`, which dropped support for v12. Would love the ability to specify which version of `firebase-tools` the action uses while we migrate to v16.

**Comment by kou65536** [comment] 2022-05-19 07:19
:+1:
My team also faced this problem and manually deploy as workaround.

**Comment by ustun** [comment] 2022-05-20 12:24
@nappernick Can you install node 14 or later, just before the actions deploy action runs?

**Comment by sergeimelnik1980** [comment] 2022-05-23 09:42
Yes, we also faced deployment problem on 12  version :(

**Comment by angelcervera** [comment] 2022-06-16 07:21
The problem is because it is installing the last version of firebase and support for nodejs 12 has been dropped.
Is there a way to specify the firebase cli version to use? Using version 10.9.2 will fix the problem. Moving to nodejs 14 is not so easy.

**Comment by ustun** [comment] 2022-06-16 13:16
This action is not official, but one would expect a little bit more support from Firebase team. As it is, the repo seems to be abandoned and as such we have forked it internally.

**Comment by bkendall** [comment] 2022-10-14 20:21
The version of firebase-tools can now be specified, if you need to stick on an older version.

**Closed by bkendall** 2022-10-14 20:21 UTC
Labels: bug
